### ISSUE TITLE
after signing up for the newsletter, I got 404

### ISSUE THREAD

**Issue by jfilter** [FixMyBerlin/fixmy.frontend#1]
![screen shot 2018-05-05 at 13 08 54](https://user-images.githubusercontent.com/3450307/39662672-dbcc5e4a-5065-11e8-96ca-7e1be73b5f23.png)

**Comment by hekele** [comment]
Sorry for the late response. We had fixed this issue by committing a thank you page here: https://github.com/FixMyBerlin/fixmy.frontend/blob/master/public/markdown/newsletter-thank-you.md
