### ISSUE TITLE
Geolocation Request Fails in some clients 

### ISSUE THREAD

**Issue by geomC** [FixMyBerlin/fixmy.frontend#13]
Noticed in MacOS Chrome

**Comment by geomC** [comment]
Fails in Firefox with Status Code 1 ..

> user denied geolocation prompt

and in Chrome with error code 2 

> Network location provider at 'https://www.googleapis.com/' : No response received.

Geolocation usage seems to have been dropped for sites not served via https

https://github.com/mdn/sprints/issues/1032
https://developers.google.com/web/updates/2016/04/geolocation-on-secure-contexts-only

**Comment by moklick** [comment]
This was not a bug but a feature of the OS. Location Services needs to be activated on MacOS.
