### ISSUE TITLE
Desktop: When detailView component is folded out, the top section is overlapped

### ISSUE THREAD

**Issue by geomC** [FixMyBerlin/fixmy.frontend#26]
![image](https://user-images.githubusercontent.com/12786207/57586061-59dadf00-74f0-11e9-9fe0-4ae262f6906a.png)

![image](https://user-images.githubusercontent.com/12786207/57586069-72e39000-74f0-11e9-94a1-cfaaf9ca50b9.png)

**Comment by geomC** [comment]
Actually covering the add and locate-me button seems legit, the optical collision in the top is more of a problem
![image](https://user-images.githubusercontent.com/12786207/57985496-1f7dbe80-7a69-11e9-8674-8e51cc7748d0.png)

Updated the problem description

**Comment by geomC** [comment]
Collapsing the navbar when a the `detailView` shows a report is not straightforward. Maybe hiding the navBar for desktop views is a better solution.

**Comment by geomC** [comment]
That would look like so: 
![image](https://user-images.githubusercontent.com/12786207/57985650-56ed6a80-7a6b-11e9-83b6-f4d8737a3167.png)

One could argue that the map needs a title. Not sure where to put this.

**Comment by moklick** [comment]
I updated the markup so that the navbar is a level higher in the DOM.
