### ISSUE TITLE
Anpassungen Landing Page

### ISSUE THREAD

**Issue by hekele** [FixMyBerlin/fixmy.frontend#27]
/meldungen/radbuegel/friedrichshain-kreuzberg/landing

- [x] "Jetzt mitmachen" falsch verlinkt -> richtig: meldungen/radbuegel/friedrichshain-kreuzberg/karte
- [x] Text FAQ Padding fehlt mobil
- [x] "Wie läuft das ab?": 4. Bullet: Alle Meldungen bekommen öffentliches Feedback auf der Plattform.
- [x] "Hier geht’s zum aktuellen Stand der Umfrage >" raus
- [x] Zeilenabstand Fliesstext sollte größer (22pt oder 1,37) Zeilenabstand Überschriften ebenso (30pt oder 1,37)
- [x]  “Sag uns wo” Button hat keinen Hovereffekt

**Comment by geomC** [comment]
Zu 1.: Die Idee war ursprünglich, dass nur der Link *Hier geht’s zum aktuellen Stand der Umfrage* zur Karte führt, und alle anderen Buttons nach [/neu](http://localhost:8080/meldungen/radbuegel/friedrichshain-kreuzberg/neu/)

Sollen dann jetzt alle Buttons zur Karte führen?

**Comment by hekele** [comment]
zu 1: Alle Links auf der Landing-Page sollen auf die Karte führen, da schien es zwischen @Hejco und Dir ein Missverständnis gegeben zu haben.
