### ISSUE TITLE
Anpassungen/Bugs zu Meldung neuer Radbügel

### ISSUE THREAD

**Issue by hekele** [FixMyBerlin/fixmy.frontend#28]
/meldungen/radbuegel/friedrichshain-kreuzberg/neu
- [x] wischen schwierig, mobil kaum benutzbar (marker lässt keine touch events auf karte durch)
- [x] Die Seite sitzt bei Schritt "Foto & Beschreibung" zu weit unten.
- [x] Ausschnitt des Fotos müsste sich anpassen nach dem Upload. 
- [x] "Foto aufnehmen" nicht verlinkt.
- [x] Newsletter: Bitte Double Opt In (checkbox nicht defaultmäßig anhaken)

**Comment by geomC** [comment]
1. Was meinst Du? Die Bedienung des Sliders zum Auswählen eines Zahlenwerts?
2. @Hejco Kannst Du bitte den Mapbox Style anpassen?

**Comment by hekele** [comment]
"Wenn ich eingeloggt bin, wird das beim letzten Schritt nicht beachtet" bespreche ich noch mal mit Stefan, ob das schon abgebildet ist.

**Comment by geomC** [comment]
bzgl.
> Die Seite sitzt bei Schritt "Foto & Beschreibung" zu weit unten.
Sollte sich mit dem Umsetzen der aktualisierten Layouts lösen. Ist in der Pipeline.

**Comment by geomC** [comment]
>Die Seite sitzt bei Schritt "Foto & Beschreibung" zu weit unten.

Fixed: https://github.com/FixMyBerlin/fixmy.frontend/commit/bd9e2b05d3b4e7f74565f87a0d8ca1c9d935163f
