### ISSUE TITLE
Anpassungen Übersicht Karte

### ISSUE THREAD

**Issue by hekele** [FixMyBerlin/fixmy.frontend#30]
/meldungen/radbuegel/friedrichshain-kreuzberg/karte
- [x] Bilder sollten verlinkt sein
- [x] Bilder sind zu groß
- [x]  Details ändern sich nicht, wenn ich die Marker nach und nach durchklicke

**Comment by geomC** [comment]
Ein paar Rückfragen dazu:

1. Meint das diese in Zeplin beschriebenen Zustände?:
```
Status Meldung neu:
- Status Meldung wird umgesetzt:
- Status Meldung wird nicht umgesetzt:
- Status Meldung wurde umgesetzt:
```
Wenn ja: 
a) Das Status Feld fehlt derzeit noch am Model.
b) Was ist mit Filter gemeint? Ein UI-Component wie dieser hier?
![image](https://user-images.githubusercontent.com/12786207/57970237-42cc3f00-797f-11e9-9ea7-dd7af8e4ea01.png)

3. Was meinst Du? Sollen die Bilder weniger Höhe bekommen?
![image](https://user-images.githubusercontent.com/12786207/57970257-73ac7400-797f-11e9-90c1-c97eb9a1d835.png)

4. Kann ich nicht reproduzieren (Desktop-Chrome + Android Chrome)

**Comment by hekele** [comment]
"Ein Filter für Status wäre super" wäre ein neues Feature

**Comment by hekele** [comment]
Mit Verlinkung des Bildes meinte ich Verlinkung auf die Detail View nicht auf die Maximierung des Bildes :-)

**Comment by geomC** [comment]
@hekele : schau mal ob es jetzt passt https://github.com/FixMyBerlin/fixmy.frontend/commit/5543db9c43f1252026bbdd7b8af941e526285c44
