### ISSUE TITLE
Zwischenseite zur Auswahl Adresse oder Geo raus

### ISSUE THREAD

**Issue by hekele** [FixMyBerlin/fixmy.frontend#31]
Die finde ich überflüssig, wenn Suche und Fadenkreuz immer angezeigt werden.

**Comment by geomC** [comment]
Suche ist derzeit nicht sichtbar, wenn die "Geo-Option" in der Zwischenseite verwendet wird.

**Comment by geomC** [comment]
Ist das mit @Hejco abgestimmt?

**Comment by hekele** [comment]
Die Seite bleibt erst mal.
