### ISSUE TITLE
Anpassungen Setzen des Markers

### ISSUE THREAD

**Issue by hekele** [FixMyBerlin/fixmy.frontend#41]
- [x] Zoom Controls fehlen komplett
- [x] Verlassen des Dialogs geht nicht
- [x] Beim Zoomen ändert sich die Straße (reverse geocoding) nicht, obwohl das Fadenkreuz wandert.
fixed: https://github.com/FixMyBerlin/fixmy.frontend/commit/3c551ef3c50031a46cfa0d2b3808975f67806c32

**Comment by geomC** [comment]
@hekele Bzgl.

> Verlassen des Dialogs geht nicht

Geht per backButton im Browser bzw. vom Telefon. Laut Designs gibt es hier keinen. Könnte oben einen Zurück-Pfeil o.ä. hinsetzen. Was meinst Du?

> Zoom Controls fehlen komplett

Laut Design ebenfalls nicht vorgesehen. Wenn doch, wo sollen sie hin?

**Comment by geomC** [comment]
Habe mich dafür entschieden, die ZoomControls auf desktop unten-rechts und mobil wie besprochen oben-links zu platzieren, dann aber den GeoCoder nach rechts rüberzuschieben.

Zu sehen in der der Deploy Preview auf https://feedback-ba--fixmyberlin-app.netlify.com/meldungen/radbuegel/friedrichshain-kreuzberg/neu/1

@Hejco  Ist das ein akzeptabler Fix?

![image](https://user-images.githubusercontent.com/12786207/64205493-6e285a80-ce98-11e9-95ae-44748ad1057a.png)


![image](https://user-images.githubusercontent.com/12786207/64205355-0d008700-ce98-11e9-974a-ebb5e92b9cd2.png)

**Comment by geomC** [comment]
ZoomControls werden dargestellt. Die gewünschte Positionierung wäre ein extra Ticket, schließe das Issue erstmal
