### ISSUE TITLE
add clustering of Reports on map

### ISSUE THREAD

**Issue by Hejco** [FixMyBerlin/fixmy.frontend#44]
enable mapbox feature to cluster reportpins on zoom
Layout: https://zpl.io/boLgLgX

- [x] decrease size of pins to 40x50px 

- [x] adjust the clustering of reports according to the Layout:
- inner and outer ring 3pt / 30% #bikeindex-3, shadow 30% #bikeindex-3 blur 10
- Size relative to number of reports 0-9 = 40px, 10-24 =50px, >24 = 60 px

- [ ] Prio B: enable clustering by geoareas by the LOR definitions (Layer "lor-friedrichshain-kreuzberg" in mapbox)

**Comment by moklick** [comment]
Clustering is implemented but not activated yet.

**Comment by moklick** [comment]
Could we create a new ticket for the geoarea clustering, so we could close this one and merge it? It's a more complicated tasks and if I see it right, we don't have the data we need at this point.
