### ISSUE TITLE
Refactor Reports: Render `ErrorMessage` component only one time at top-level

### ISSUE THREAD

**Issue by s-pic** [FixMyBerlin/fixmy.frontend#576]
Propably at [/src/pages/Reports/Reports.js](https://github.com/FixMyBerlin/fixmy.frontend/blob/develop/src/pages/Reports/Reports.js)

**Comment by cafca** [comment]
@s-pic I am not sure about the exact purpose of this. Why do we want to have the error message component at a top level?

**Comment by s-pic** [comment]
@cafca This ticket has been created at a time where I tought we'd need a global error / errors state sclice. Now we have discussed that we move forward by using an error slice per page (for every key in the root state slice).

So I am closing this.
