### ISSUE TITLE
Anpassungen nach Feedback BA und Usertests

### ISSUE THREAD

**Issue by Hejco** [FixMyBerlin/fixmy.frontend#58]
Updates und Anpassungen nach Usertests und Feedback von Bezirksamt Friedrichshain-Kreuzberg.

### Menu / Sidebar https://zpl.io/aByEYqA
- [x] Benennung und Icons der Menupunkte nach Layout (webkid)
- [x] Foldoutmenu für "Mitmachen" (webkid)
- [x] New Exit Button

### Landingpage https://zpl.io/bWkvZmj
- [x]  Hinweis „Mehr Infos“ + shader einbauen.
- [x] Grafiken Schritte "Wie läuft das ab
- [x] Texte: Div. wording updates (Update von BA XHain)
- [x] Buttons verlinkung alle auf "Meldung 1" + Buttontext updates 
- [x] prioA: Foto Weissbrich einsetzen **waiting for BA-XHain**
- [x] prioA: hinzufügen von Links zur Karte "Schau dir die Meldungen Anderer an"

### Meldung 1 https://zpl.io/Vx1eYK3
- [x] Add Exit Button
- ~~Ausblenden der Titelzeile (map-Hintergrund)~~ *zurückgestellt, da aufwändiger*

### Meldung 1a https://zpl.io/agPeBZO
- [x] Schwebenden Marker entfernen
- [x] Weisser Hintergrund (70% transparent) hinter Adressangabe

### Meldung 1b https://zpl.io/V0RejdE
- [x] new exit Button, (inkl. Text "abbrechen" )

### Meldung 2 https://zpl.io/amyNn1K
- [x] new exit Button
- [x] prioA: Auswahl Straße - Gehweg entfernen
- [x] prioA: Infos und Bild "Bügel auf Straße" hinzufügen
- [x] prioA: max Nummer an Bügeln = 12
- [ ] prio B: Der Slider wäre noch besser zu bedienen, wenn während des Verschiebens die ausgewählte Zahl oberhalb des Fingers groß eingeblendet würde (ähnlich iphone Tastatur)

### Meldung 3 https://zpl.io/brl6Nkr
- [x] new exit Button
- [x] prioA: Wording Updates
- [x] prioA: Eingabe Feld größer
- [ ] Uploader: Label über Control positionieren

### Meldung 4 https://zpl.io/amdM30A
- [x] new exit Button
- [x] prioA: Wording Updates
- [x] prioA: Geldoption entfernen
- [x] prioA: Foto Parkhaus  hinzufügen
- [x] prioA: "weitere Informationen" hinzufügen

### Meldung https://zpl.io/a75KEzj
- [x] prioA: Reihenfolge Mailadresse und "Meldung ansehen" ändern
- [x] Aktualisiertes Layout Eingabefeld Email
- [x] prioA: Button Meldungen ansehen Style secondary.
- [ ] prioA: "ansehen" verlinkt auf: map/meldungen/flyout **[Sascha]: Aufwändig!**
- [x] prioA: Wording Updates
- [x] prioA: add lines
- [x] prioA: Füge Option bestehendes Login hinzu.
- [x] prioA: Füge Grafik "Danke" hinzu 

### map/meldungen https://zpl.io/VKoOkZq 
- [ ] prio B: Farbgebung nach Status hinzufügen (Definition von Status und Farbzuordnung in Zeplin)
- [ ] prio B: Haken bei Pin Status "umgesetz" hinzufüge

### map/meldungen/flyout https://zpl.io/VQKo9oR 
- [x] new exit Button
- [x] prio A: Wording "gewünscht"
- [ ] Likebutton hinzufügen
- [ ] prio A: change size & spacing 
(Styles can be transfered to planningsmap later)

### map/meldungen/detail https://zpl.io/VOm6RZj 
- [x] new exit Button
- [x] prio A: Wording Updates
- [x] prio A: add lines
- [x] prio A: add Pin for status (Colorcoding can be done later)
- [ ] smaler Styleupdates
- [ ] Kommentarfeld hinzufügen (can be done later)
- [ ] timestamps hinzufügen
- [x] prio A: aktualisierte Like/ Teilen box - Box sollte permanent zu sehen und unten angeheftet sein.

**Comment by geomC** [comment]
Working on this in https://github.com/FixMyBerlin/fixmy.frontend/tree/feedback-ba

**Comment by geomC** [comment]
Fast alle PrioA Themen sind abgearbeitet. Schließe das Ticket nach Absprache mit @hekele
Was liegen geblieben ist kann in neue Tickets.
