### ISSUE TITLE
Replace fetch-mock with msw

### ISSUE THREAD

**Issue by s-pic** [FixMyBerlin/fixmy.frontend#591]
# Story
Instead of specifically mocking fetch/axios/ky/whatever in our tests, we can use [msw ](https://github.com/mswjs/msw) to
intercept http requests and answer them with mock data **on network level** instead of application level. By making our tests agnostic to the http library issuing the request, we can easily replace that lib. Furthermore, msw can be used during development, e.g. to develop against an endpoint that does not exist yet.
See https://kentcdodds.com/blog/stop-mocking-fetch/ for a high level introduction to msw.

We introduced msw in https://github.com/FixMyBerlin/fixmy.frontend/pull/490, so we can use the existing setup.

**Comment by ohrie** [comment]
Closing this, since fetch-mock is not an dependency of the project anymore, but msw is.
