### ISSUE TITLE
Feelsafe index is not displayed correctly in some browsersizes

### ISSUE THREAD

**Issue by Hejco** [FixMyBerlin/fixmy.frontend#596]
<img width="921" alt="Bildschirmfoto 2020-09-03 um 17 31 16" src="https://user-images.githubusercontent.com/39826825/92385062-78b3aa80-f111-11ea-9dc3-8f3a8713fe84.png">
the feelsafeindex is displayed with overlaps in a specific width of the browserwindow (FF 80.0.1, OSX, Browser width 1000px)

solution? index-ring should scale with browserwidth.

**Comment by ohrie** [comment]
Since KatasterKI is stale, it is currently not developed in the near future.
Closing this for now, but possible reopen in the future.
