### ISSUE TITLE
KatasterKI e2e CI fails at scene tests

### ISSUE THREAD

**Issue by cafca** [FixMyBerlin/fixmy.frontend#598]
Link to error in ci https://github.com/FixMyBerlin/fixmy.frontend/pull/532/checks?check_run_id=1143010533#step:8:379

It works on my machine though

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/278463/93769947-d967da80-fc1b-11ea-8034-f632c3a5e8cd.png">

**Comment by ohrie** [comment]
Closing this, since the project is stale. Reopen when needed.
