### ISSUE TITLE
Liste von gelikeden Planungen zeigt keine Planungen an.

### ISSUE THREAD

**Issue by Hejco** [FixMyBerlin/fixmy.frontend#61]
Bei anzeige des Profils, werden unter dem Reiter "Likes" keine Planugnen angezeigt, obwohl mehrere Planungen geliked wurden. https://fixmyberlin.de/profil Account: info@heikorintelen.de (FF, OSX)

**Comment by chrtze** [comment]
Das Problem ist, dass bei der response von https://api.fixmyberlin.de/api/plannings das flag `liked_by_user` offenbar nicht auf `true` gesetzt wird obwohl vorher die Planung geliked wurde. @freudenberg @hekele 

Bei der Einzelansicht funktioniert es, die Logik ist allerdings nicht übertragbar auf die User Ansicht.
