### ISSUE TITLE
UX flaws in viewing the details of a clustered report/planning in Aachen's report map

### ISSUE THREAD

**Issue by s-pic** [FixMyBerlin/fixmy.frontend#611]
# What is the problem?

If I open a planning via deep-link
(e.g. https://radbuegel-aachen.de/meldungen/karte/1838),
I cannot spot the requested feature on the map.
The map item is part of a cluster, so I cannot spot the single geometry.
Even if I zoom in, the feature is not highlighted, it just looks like "all other features".

The same problem applies if I click on another feature that is part of a cluster

![GIF 30 10 2020 20-12-59](https://user-images.githubusercontent.com/12786207/97747503-5ffdba80-1aec-11eb-84d3-cffdb8b3234e.gif)

# What is the expected result?

* if I use a deep-link
  * the map will zoom in until no map items are clustered
  * the inspected feature is emphasized, e.g. by making it bigger or adding some sort of halo to it.

# Background
Sumbled upon this while working at https://github.com/FixMyBerlin/fixmy.frontend/issues/568

**Comment by cafca** [comment]
Thank you for writing this up!
