### ISSUE TITLE
Setup Sentry to collect information about exceptions on user's clients

### ISSUE THREAD

**Issue by cafca** [FixMyBerlin/fixmy.frontend#619]
This issue asks to create a WIP-PR that contains a working Sentry configuration in order to further evaluate Sentry with regards to their privacy protection features.

**Comment by ohrie** [comment]
@s-pic  Since we are now again evaluating sentry for error tracking and performance tracking: Have you had any progress on this issue?

**Comment by s-pic** [comment]
Well we tried it out and it looked promising. Bit I think we never started using it.
