### ISSUE TITLE
Sammelticket Bugs Meldedialog

### ISSUE THREAD

**Issue by Hejco** [FixMyBerlin/fixmy.frontend#65]
Menu:
- [ ] Leerstelle zwischen "Fahrradbügel" und "in" fehlt

Landingpage:
- [x] Grafik "Ablauf" wird abgeschnitten
- [x] shader mehr Infos sollte dunkler (mobile nicht zu erkennen)

Positionsbestimmung:
- [x] Aufhellung wird über die ganz Karte gelegt (DT)
- [x] Bei der Bestätigung der Position immer noch flasches Buttondesign. https://zpl.io/V0RejdE

**Comment by geomC** [comment]
Hallo @Hejco, ein paar Rückfragen dazu:

>  Leerstelle zwischen "Fahrradbügel" und "in" fehlt

Das Menü habe ich nicht angefasst, dachte das geht an WebKid

> Aufhellung wird über die ganz Karte gelegt (DT)

Meinst Du die halbtransparent-weiße Fläche hinter der Schrift? Die sieht auch auf Desktop (DT?) okay aus 
.
![image](https://user-images.githubusercontent.com/12786207/64129931-7a8cb480-cdbf-11e9-8a1c-5bab7b54d90d.png)


>  Bei der Bestätigung der Position immer noch flasches Buttondesign.

Umsetzung entspricht mE der Vorlage: https://app.zeplin.io/project/5ad5f75adf221b9343d45559/screen/5c0fb776e032f3507eed53cc

Was hier noch fehlt ist 
![image](https://user-images.githubusercontent.com/12786207/64129944-942dfc00-cdbf-11e9-8de3-208bd66455c6.png)

**Comment by geomC** [comment]
@Hejco Kann das geschlossen werden?
