### ISSUE TITLE
Ausspielen des Datums Meldungen im Backend

### ISSUE THREAD

**Issue by Hejco** [FixMyBerlin/fixmy.frontend#67]
Der Zeitpunkt der Meldung soll im Backend ausgegeben werden, so dass dieser bei der Detailansicht der Meldungen mit angezeigt werden kann (https://zpl.io/VOm6RZj). Ebenso sollte das Datum der letzten Aktualisierung einer Meldung (wenn, diese einen neuen Status oder einen Kommentar erhält) ausgegeben werden.  Format TT.MM.JJJJ

**Comment by freudenberg** [comment]
Ich habe die Attribute created_date und modified_date zur JSON-Repräsentation der Meldungen hinzugefügt.
