### ISSUE TITLE
Contribution Possible?

### ISSUE THREAD

**Issue by geomC** [FixMyBerlin/fixmy.frontend#7]
Hi there,

my name is Sascha and I am a Berlin-based web-GIS developer.
I am currently learning React/Redux and was looking for an exercise project going in the same direction of this awesome project, which I found just now.
I am into bike politics and would like to see this app grow.

Is it possible to contribute to the project in any way?

**Comment by hekele** [comment]
Hi Sascha,

yes sure, that would be possible. We work open source and still have some new features to develop like a light weight „Mängelmeldsystem“ :-) Or simply a list of all plannings liked by a user. We could talk during the week if you want? On the 23rd there is our Fahrraddaten Meetup you may want join? https://www.meetup.com/de-DE/Datacycle-Meetup-Fahrraddaten-fur-Berlin/ <https://www.meetup.com/de-DE/Datacycle-Meetup-Fahrraddaten-fur-Berlin/> 

Best, Boris

**Comment by geomC** [comment]
Hi Boris,

awesome! I will come to the meetup and then we can talk.

BTW: IMHO a "Mängelmeldsystem" is a great thing to add.

**Comment by hekele** [comment]
Perfect!
