### ISSUE TITLE
Add Feedback Link

### ISSUE THREAD

**Issue by Hejco** [FixMyBerlin/fixmy.frontend#70]
Bei der Kartenansicht soll den Nutzer:innen die Möglichkeit gegeben werden eine Feedback Mail zum Meldedialog zu versenden.

Dafür soll ein Link eingefügt werden entsprechend Layout https://zpl.io/VKoOkZq 

Der Klick darauf öffnet eine Email an feedback@fixmyberlin.de mit dem Betreff "Feedback zum Meldedialog"

**Comment by geomC** [comment]
Kann ich die Woche noch fertig stellen. 

Vorschlag für Wording: "Feedback zum Meldedialog?" (ohne "Dein")

Vorschlag für Positionierung auf DT:
![image](https://user-images.githubusercontent.com/12786207/64288780-363a1980-cf63-11e9-8672-6e5cce192d2d.png)
