### ISSUE TITLE
Textgröße und -schnitt bei Checkboxen angleichen (auf die für den Login)

### ISSUE THREAD

**Issue by hekele** [FixMyBerlin/fixmy.frontend#86]
![grafik](https://user-images.githubusercontent.com/474596/64453962-12551000-d0ea-11e9-985d-798506bd9208.png)
![grafik](https://user-images.githubusercontent.com/474596/64454385-22b9ba80-d0eb-11e9-9dc5-96a0f7ca497c.png)

**Comment by geomC** [comment]
Das selbe Problem besteht beim Email-Input, der eigentlich auch einen anderen Stil haben sollte,
siehe #68 (ganz unten im Issue Body).

**Comment by moklick** [comment]
In den Inputs wollten wir Schriftgröße 16px behalten, damit auf iOS nicht gezoomt wird.
