### ISSUE TITLE
Change spelling for infrastructure ministry from BMVI to BMDV 

### ISSUE THREAD

**Issue by ohrie** [FixMyBerlin/fixmy.frontend#933]
## Issue description
After election the BMVI is now called `BMDV` (Bundesministerium für Digitales und Verkehr). The according texts and images need to be replaced.

See occurences "BMVI": https://github.com/FixMyBerlin/fixmy.frontend/search?q=bmvi

## Tasks
- [ ] Replace texts
- [ ] Replace Images

**Comment by ohrie** [comment]
@tordans Has there been any work done yet on this issue?

**Comment by tordans** [comment]
No, just a global search to find potential places to fix https://github.com/search?q=org%3AFixMyBerlin+BMVI&type=code

**Comment by ohrie** [comment]
Alright done that in #935
