### ISSUE TITLE
Willkommen-Overlay umsetzen + "Beta" vom Logo weg

### ISSUE THREAD

**Issue by tordans** [FixMyBerlin/fixmy.frontend#943]
# Acceptance Criteria (AC)

**Prio 1**

- [x] Bei jedem Seitenaufruf wird der Overlay angezeigt
  - [x] Abschalten über Schließen-X
- [x] "Beta" vom Logo entfernen, da jetzt im Overlay erklärt
- [x] Nur anzeigen, wenn Karte auf Index aufgerufen wird; nicht wenn ein Deeplink verwendet wird

**Prio 2**

- [x] Abschalten zusätzlich auch über "Click außerhalb des Feldes" und über "Esc"-Tastatur
- [x] Demo-Links im Text linken in die Karte hinein

# Wireframe 
- Desktop https://app.zeplin.io/project/5ad5f75adf221b9343d45559/screen/602181d8d2f5355f2797a195
- Mobile https://app.zeplin.io/project/5ad5f75adf221b9343d45559/screen/602183b1e9271d15335ac7a5

**Comment by ohrie** [comment]
Introduced first in 735ba79b68956aa4cb1e447abec11c67e4bd9973 , changed in 3bd478a1df7a9411e414aef9968e0966ef8ed1e5
