### ISSUE TITLE
Images in Markdown files cannot be resolved by webpack

### ISSUE THREAD

**Issue by tordans** [FixMyBerlin/fixmy.frontend#963]
# Issue

https://fixmyberlin-staging.netlify.app/404
https://deploy-preview-957--fixmyberlin-staging.netlify.app/404

both do not show the image but  https://fixmyberlin.de/404 does.

# Notes

Likely related to the recent webpack update to v5?

**Comment by ohrie** [comment]
Same on the imprint: https://fixmyberlin-staging.netlify.app/impressum
-> Markdown files with images could be a problem in general :/

**Comment by ohrie** [comment]
The images are indeed available:https://fixmyberlin-staging.netlify.app/src/images/partner/bmdv-gefoerdert.png

**Comment by ohrie** [comment]
Works, when removing the `transformImageUri={loadImage}` in
https://github.com/FixMyBerlin/fixmy.frontend/blob/3f19aed41666b3732c2c34f0d9dbbb1b921859a4/src/pages/Markdown/components/MarkdownContent.js#L61-L63

Not sure, what side effects this could have.

**Comment by tordans** [comment]
https://github.com/remarkjs/react-markdown#props has a bit about `transformImageUri` but nothing that would help a lot…

**Comment by ohrie** [comment]
> https://github.com/remarkjs/react-markdown#props has a bit about `transformImageUri` but nothing that would help a lot…

Yeah, this page was the hint to think about this property :)
