### ISSUE TITLE
Anpassungen nach testing

### ISSUE THREAD

**Issue by Hejco** [FixMyBerlin/fixmy.frontend#967]

**Comment by Hejco** [comment]
- [ ] Inhaltsverzeichnis Textupdate
- [ ] zweite Spalte in Legende linksbündig (boxen mit festen variablen Breiten)
<img width="854" alt="Bildschirmfoto 2022-01-27 um 16 37 25" src="https://user-images.githubusercontent.com/39826825/151391530-277b3247-1f3c-4810-9866-c9c04eb79003.png">

- [ ] Die Hinweise als kursive Schrift
- [ ] Bei Legende in Karte Maßnahmen "Lichtsignalanlagen"
- [ ] Bei klick auf mailto: sollte als Adressat "Straßen- und Grünflächenamt FH" stehen statt Tiefgruen

**Comment by tordans** [comment]
Update: https://deploy-preview-957--fixmyberlin-staging.netlify.app/schulwegsicherheit/friedrichshain-kreuzberg
