### ISSUE TITLE
Ich kann das ausgesuchte Foto zur Meldung nicht löschen

### ISSUE THREAD

**Issue by hekele** [FixMyBerlin/fixmy.frontend#97]
Es müsste die Möglichkeit geben das ausgesuchte Foto auch wieder löschen zu können, da man sonst in einer Sackgasse ist, wenn man das Foto doch nicht submitten will.

**Comment by geomC** [comment]
@hekele or @Hejco 
Bitte kurzes Feedback zum Abbrechen Button, entweder via Deploy Preview oder folgenden Screenshot:

![image](https://user-images.githubusercontent.com/12786207/64563388-89d7a900-d34f-11e9-842c-ec8b5e9f8f8a.png)

Bei sehr breiten Bildern wird der Abstand zwischen Button und Photo recht groß, das ist aber schwer anders zu lösen.
